accelerator: gpu
accumulate_grad_batches: null
amp_backend: null
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: null
batch_size: 64
benchmark: null
betas: !!python/tuple
- 0.8
- 0.99
c_kl: 1.0
c_mel: 45
channels: 1
check_val_every_n_epoch: 1
checkpoint_epochs: 1
dataset:
- !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - hansenm
  - larynx2
  - local
  - en-us
  - libritts
  - high
  - dataset.jsonl
dataset_dir: &id001 !!python/object/apply:pathlib.PosixPath
- /
- home
- hansenm
- larynx2
- local
- en-us
- libritts
- high
default_root_dir: *id001
detect_anomaly: false
devices: '1'
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
eps: 1.0e-09
fast_dev_run: false
filter_channels: 768
filter_length: 1024
gin_channels: 0
gpus: null
grad_clip: null
gradient_clip_algorithm: null
gradient_clip_val: null
hidden_channels: 192
hop_length: 256
inference_mode: true
init_lr_ratio: 1.0
inter_channels: 192
ipus: null
kernel_size: 3
learning_rate: 0.0002
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 50
logger: true
lr_decay: 0.999875
max_epochs: 10000
max_phoneme_ids: 500
max_steps: -1
max_time: null
mel_channels: 80
mel_fmax: null
mel_fmin: 0.0
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_heads: 2
n_layers: 6
n_layers_q: 3
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
num_speakers: 904
num_symbols: 130
num_test_examples: 0
num_workers: 1
overfit_batches: 0.0
p_dropout: 0.1
plugins: null
precision: 32
profiler: null
quality: high
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resblock: '1'
resblock_dilation_sizes: !!python/tuple
- &id002 !!python/tuple
  - 1
  - 3
  - 5
- *id002
- *id002
resblock_kernel_sizes: !!python/tuple
- 3
- 7
- 11
resume_from_checkpoint: lightning_logs/version_1/checkpoints/epoch=63-step=387320.ckpt
sample_bytes: 2
sample_rate: 22050
seed: 1234
segment_size: 8192
strategy: null
sync_batchnorm: false
tpu_cores: null
track_grad_norm: -1
upsample_initial_channel: 512
upsample_kernel_sizes: !!python/tuple
- 16
- 16
- 4
- 4
upsample_rates: !!python/tuple
- 8
- 8
- 2
- 2
use_sdp: true
use_spectral_norm: false
val_check_interval: null
validation_split: 0.01
warmup_epochs: 0
win_length: 1024
